include:
  - package:bloc_lint/recommended.yaml
  - package:dart_frog_lint/recommended.yaml
  - package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    diagnostic_describe_all_properties: ignore
