name: authentication_repository
description: Repository that manages the authentication domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  api_client: ^0.1.0
  logging: ^1.3.0
  models: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
