name: semantic_pull_request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      pull-requests: write
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
